Vagrant.configure("2") do |config|

    (1..3).each do |i|

        config.vm.define "node#{i}" do |node|

        # box
        # node.vm.box = "ubuntu/trusty64"
        node.vm.box = "centos/7"


        # hostname
        node.vm.hostname="node#{i}"

        # ip
        node.vm.network "private_network", ip: "192.168.66.#{10+i}"

        # share folder
        node.vm.synced_folder "~/project", "/project"

        # box provider chose VirtaulBox
        node.vm.provider "virtualbox" do |v|

            # box name
            v.name = "node#{i}"

            # memory
            v.memory = 1024

            # cups
            v.cpus = 1
        end
  
        # provision script
        config.vm.provision :shell, path: "bootstrap.sh"

        end
    end
end